### ISSUE TITLE
can you update krita version to 5.2.3

### ISSUE THREAD

**Issue by da-peng** [linuxserver/docker-krita#4]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

update krita verison to 5.2.3 and update docker images

### Reason for change

updat krita verison to 5.2.3 and update docker images

**Comment by j0nnymoe** [comment]
We use the alpine packages for this container, currently still at 5.2.2. 
https://pkgs.alpinelinux.org/packages?name=krita&branch=v3.20&repo=&arch=&maintainer=
Once they've been updated, the container will receive the update.
